steps:
  - subject: add.tracing
    pattern: request
    direction: incoming
    order: 1

  - subject: '*'
    pattern: request
    direction: incoming
    order: 2
observers:
  - subject: 'logging'
  - subject: 'record.metrics'