steps:
  - subject: trace.header
    pattern: request
    direction: incoming
    order: 1

  - subject: authentication
    pattern: request
    direction: incoming
    order: 2

  - subject: '*'
    pattern: request
    direction: incoming
    order: 3
observers:
  - subject: 'pipeline.logging'
  - subject: 'pipeline.metrics'